package com.bellizia.owcompanion.ui.meta

/**
 * A map the rates page can be scoped to, and the mode it is played in.
 *
 * Generated by tools/make_maps.py from Blizzard's own map dropdown joined with OverFast's
 * game modes - edit that, not this. Names stay in English because that is what the rates
 * page is keyed on.
 */
data class MetaMap(val slug: String, val label: String, val mode: String)

/** Every map the rates page will filter by, grouped by mode in the order shown. */
val MetaMaps: List<MetaMap> = listOf(
    MetaMap("antarctic-peninsula", "Antarctic Peninsula", "control"),
    MetaMap("busan", "Busan", "control"),
    MetaMap("ilios", "Ilios", "control"),
    MetaMap("lijiang-tower", "Lijiang Tower", "control"),
    MetaMap("nepal", "Nepal", "control"),
    MetaMap("oasis", "Oasis", "control"),
    MetaMap("samoa", "Samoa", "control"),
    MetaMap("circuit-royal", "Circuit royal", "escort"),
    MetaMap("dorado", "Dorado", "escort"),
    MetaMap("havana", "Havana", "escort"),
    MetaMap("junkertown", "Junkertown", "escort"),
    MetaMap("rialto", "Rialto", "escort"),
    MetaMap("route-66", "Route 66", "escort"),
    MetaMap("shambali-monastery", "Shambali Monastery", "escort"),
    MetaMap("watchpoint-gibraltar", "Watchpoint: Gibraltar", "escort"),
    MetaMap("blizzard-world", "Blizzard World", "hybrid"),
    MetaMap("eichenwalde", "Eichenwalde", "hybrid"),
    MetaMap("hollywood", "Hollywood", "hybrid"),
    MetaMap("kings-row", "King's Row", "hybrid"),
    MetaMap("midtown", "Midtown", "hybrid"),
    MetaMap("neon-junction", "NEON JUNCTION", "hybrid"),
    MetaMap("numbani", "Numbani", "hybrid"),
    MetaMap("paraiso", "Paraíso", "hybrid"),
    MetaMap("colosseo", "Colosseo", "push"),
    MetaMap("esperanca", "Esperança", "push"),
    MetaMap("new-queen-street", "New Queen Street", "push"),
    MetaMap("runasapi", "Runasapi", "push"),
    MetaMap("aatlis", "Aatlis", "flashpoint"),
    MetaMap("new-junk-city", "New Junk City", "flashpoint"),
    MetaMap("suravasa", "Suravasa", "flashpoint"),
)
