# Written by tools/count_tokens.py. Read by app/build.gradle.kts.
tokens=1353542307
tokensInput=5720
tokensOutput=3052029
tokensCacheWrite=12206887
tokensCacheRead=1338277671
sessions=1
measured=2026-08-10
