# Written by tools/count_tokens.py. Read by app/build.gradle.kts.
tokens=1819997126
tokensInput=7702
tokensOutput=3892067
tokensCacheWrite=18342561
tokensCacheRead=1797754796
sessions=1
measured=2026-08-12
