# Written by tools/count_tokens.py. Read by app/build.gradle.kts.
tokens=1067385414
tokensInput=4676
tokensOutput=2573848
tokensCacheWrite=10043433
tokensCacheRead=1054763457
sessions=1
measured=2026-08-08
