"""Draws the portrait for the custom hero.

    python tools/make_custom_portrait.py

The Lab sits in the hero grid as a hero of its own, so it needs a face. This draws an
omnic-looking one out of plain shapes: a rounded faceplate, a visor band, and a row of lit
segments across it that stand for the sliders the screen is made of.

Nothing here is traced from or based on Blizzard's artwork. Every other portrait in the app
is theirs, used under the Fan Content Policy; this one is a placeholder for a hero that does
not exist, so inventing it is both easy and the only defensible option.

Writes a vector drawable, which scales to any grid size without a set of PNG buckets.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "app" / "src" / "main" / "res" / "drawable" / "portrait_custom.xml"

# The app's own orange, and the two greys the dark theme uses for raised surfaces.
PLATE = "#FF2B3038"
PLATE_EDGE = "#FF3D444F"
VISOR = "#FF16191F"
LIT = "#FFF99E1A"
DIM = "#FF6E7683"

SIZE = 128.0


def rounded(x: float, y: float, w: float, h: float, r: float) -> str:
    """A rounded rectangle as a path, which keeps the whole file to one drawable."""
    return (
        f"M{x + r},{y} h{w - 2 * r} a{r},{r} 0 0 1 {r},{r} "
        f"v{h - 2 * r} a{r},{r} 0 0 1 -{r},{r} h-{w - 2 * r} "
        f"a{r},{r} 0 0 1 -{r},-{r} v-{h - 2 * r} a{r},{r} 0 0 1 {r},-{r} z"
    )


def main() -> int:
    paths = []

    # The head: a tall rounded plate, slightly narrower at the jaw.
    paths.append((rounded(28, 18, 72, 88, 18), PLATE, None))
    paths.append((rounded(28, 18, 72, 88, 18), None, PLATE_EDGE))

    # The visor band.
    paths.append((rounded(36, 46, 56, 26, 9), VISOR, None))

    # Five lit segments, the middle three brighter: the sliders, read as a face.
    for index in range(5):
        x = 42 + index * 10
        height = 10 if index in (1, 2, 3) else 6
        y = 59 - height / 2
        colour = LIT if index in (1, 2, 3) else DIM
        paths.append((rounded(x, y, 5, height, 2), colour, None))

    # A chin vent, so the plate reads as a machine rather than a phone.
    paths.append((rounded(52, 84, 24, 8, 4), PLATE_EDGE, None))

    # The antenna, off to one side so the silhouette is not symmetrical.
    paths.append((rounded(84, 6, 6, 18, 3), PLATE_EDGE, None))
    paths.append((rounded(85, 2, 4, 6, 2), LIT, None))

    body = "\n".join(
        "    <path\n"
        f'        android:pathData="{d}"\n'
        + (f'        android:fillColor="{fill}"\n' if fill else "")
        + (
            f'        android:strokeColor="{stroke}"\n        android:strokeWidth="2"\n'
            if stroke
            else ""
        )
        + "        />"
        for d, fill, stroke in paths
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/make_custom_portrait.py. Edit that, not this. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{SIZE:.0f}dp"\n'
        f'    android:height="{SIZE:.0f}dp"\n'
        f'    android:viewportWidth="{SIZE:.0f}"\n'
        f'    android:viewportHeight="{SIZE:.0f}">\n'
        f"{body}\n"
        "</vector>\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(paths)} shapes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
