"""Draws the launcher icon.

    python tools/make_icon.py

The icon is the app's own subject rather than a badge: a burst of fire drawn the way the
damage chart draws it, four shots climbing, then the gap where the magazine runs dry, then
the first shot of the next one in a different colour. Nothing here is anyone else's - plain
rounded rectangles and two colours already used throughout the app - so there is no artwork,
mark or likeness to infringe.

Adaptive icons are 108x108 with only the centre 66 across guaranteed to survive the launcher's
mask, and the corners of that square get cut on a round mask. Everything below is therefore
placed against a circle of radius 33 and checked against it, which is what `fits` is for.

Writes the two vector drawables the launcher uses, plus a 512px PNG for the README.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "app" / "src" / "main" / "res"
DOCS = ROOT / "docs"

CENTRE = 54.0
SAFE_RADIUS = 33.0

BAR_WIDTH = 9.0
CORNER = 3.5

# (offset from centre, height). Four rising shots, a gap three times the usual, then the
# first shot of a fresh magazine. The asymmetry is the point: a symmetric peak would read as
# an audio equaliser, which is not what this app does.
BARS = [
    (-27.0, 18.0),
    (-15.0, 30.0),
    (-3.0, 44.0),
    (9.0, 58.0),
    (27.0, 16.0),
]

BURST = BBURST = slice(0, 4)
RELOAD = 4

ORANGE_LIGHT = "#FFC24D"
ORANGE_DEEP = "#E0761B"
CYAN = "#43C0E0"
NAVY = "#121A26"
NAVY_RAISED = "#2A3648"

# The burst leans, because five upright bars is an audio equaliser and this is not one. The
# tilt is applied about the centre of the canvas, which is the one transform that cannot
# push a corner outside the safe circle: rotation about the centre preserves every radius.
TILT = -9.0


def fits(offset: float, height: float) -> bool:
    """Whether a bar's furthest corner stays inside the launcher's guaranteed circle."""
    x = abs(offset) + BAR_WIDTH / 2
    y = height / 2
    return x * x + y * y <= SAFE_RADIUS * SAFE_RADIUS


def rounded_rect(x: float, y: float, w: float, h: float, r: float) -> str:
    """Vector drawables have no rounded-rect primitive, so it is drawn by hand."""
    r = min(r, w / 2, h / 2)
    return (
        f"M{x + r:.2f},{y:.2f}"
        f"h{w - 2 * r:.2f}"
        f"a{r:.2f},{r:.2f} 0 0 1 {r:.2f},{r:.2f}"
        f"v{h - 2 * r:.2f}"
        f"a{r:.2f},{r:.2f} 0 0 1 {-r:.2f},{r:.2f}"
        f"h{-(w - 2 * r):.2f}"
        f"a{r:.2f},{r:.2f} 0 0 1 {-r:.2f},{-r:.2f}"
        f"v{-(h - 2 * r):.2f}"
        f"a{r:.2f},{r:.2f} 0 0 1 {r:.2f},{-r:.2f}"
        "z"
    )


def bar_geometry() -> list[tuple[float, float, float, float]]:
    """Each bar as (x, y, w, h), vertically centred on the canvas."""
    return [
        (CENTRE + offset - BAR_WIDTH / 2, CENTRE - height / 2, BAR_WIDTH, height)
        for offset, height in BARS
    ]


def foreground() -> str:
    boxes = bar_geometry()
    burst = "".join(rounded_rect(*box, CORNER) for box in boxes[BURST])
    reload_shot = rounded_rect(*boxes[RELOAD], CORNER)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_icon.py - edit that, not this. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group
        android:pivotX="54"
        android:pivotY="54"
        android:rotation="{TILT}">

        <!-- Four rising shots, drawn as one path so the gradient runs across the burst
             rather than restarting inside each bar. -->
        <path android:pathData="{burst}">
            <aapt:attr name="android:fillColor">
                <gradient
                    android:type="linear"
                    android:startX="22.5"
                    android:startY="80"
                    android:endX="67.5"
                    android:endY="25">
                    <item android:offset="0" android:color="{ORANGE_DEEP}" />
                    <item android:offset="1" android:color="{ORANGE_LIGHT}" />
                </gradient>
            </aapt:attr>
        </path>

        <!-- The first shot after the reload: a different colour because it is a different
             magazine, which is the whole reason the gap is worth drawing. -->
        <path
            android:fillColor="{CYAN}"
            android:pathData="{reload_shot}" />
    </group>
</vector>
"""


def monochrome() -> str:
    """Themed icons are tinted flat by the launcher, so shape has to carry it alone."""
    boxes = bar_geometry()
    everything = "".join(rounded_rect(*box, CORNER) for box in boxes)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_icon.py - edit that, not this. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <!-- No tint here on purpose: the launcher applies its own, and a theme attribute would
         be resolved against the launcher's theme rather than ours. -->
    <group
        android:pivotX="54"
        android:pivotY="54"
        android:rotation="{TILT}">
        <path
            android:fillColor="#FFFFFF"
            android:pathData="{everything}" />
    </group>
</vector>
"""


def background() -> str:
    """A flat navy reads as a hole next to other icons; a soft rise gives it a centre."""
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_icon.py - edit that, not this. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="radial"
                android:centerX="54"
                android:centerY="46"
                android:gradientRadius="72">
                <item android:offset="0" android:color="{NAVY_RAISED}" />
                <item android:offset="1" android:color="{NAVY}" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
"""


def write_png(path: Path, size: int = 512) -> bool:
    """A flat copy for the README and anywhere a vector will not do."""
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        return False

    scale = size / 108.0

    def rgb(value: str) -> tuple[int, int, int]:
        return tuple(int(value[i : i + 2], 16) for i in (1, 3, 5))

    # The same radial gradient the vector describes, computed small and scaled up: at this
    # radius the interpolation is invisible and it avoids a numpy dependency.
    coarse = 96
    inner_rgb, outer_rgb = rgb(NAVY_RAISED), rgb(NAVY)
    gradient = Image.new("RGB", (coarse, coarse))
    pixels = gradient.load()
    for py in range(coarse):
        for px in range(coarse):
            dx = (px + 0.5) * 108 / coarse - 54.0
            dy = (py + 0.5) * 108 / coarse - 46.0
            t = min(1.0, (dx * dx + dy * dy) ** 0.5 / 72.0)
            pixels[px, py] = tuple(
                round(inner_rgb[c] + (outer_rgb[c] - inner_rgb[c]) * t) for c in range(3)
            )
    image = gradient.resize((size, size), Image.BICUBIC).convert("RGBA")

    bars = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(bars)

    boxes = bar_geometry()
    top = rgb(ORANGE_LIGHT)
    bottom = rgb(ORANGE_DEEP)
    for index, (x, y, w, h) in enumerate(boxes):
        if index == RELOAD:
            colour = rgb(CYAN)
        else:
            # Approximates the gradient by stepping the colour bar to bar.
            t = index / 3
            colour = tuple(round(bottom[c] + (top[c] - bottom[c]) * t) for c in range(3))
        draw.rounded_rectangle(
            [x * scale, y * scale, (x + w) * scale, (y + h) * scale],
            radius=CORNER * scale,
            fill=colour,
        )

    # Pillow rotates counter-clockwise where the vector drawable rotates clockwise.
    image.alpha_composite(bars.rotate(-TILT, resample=Image.BICUBIC, center=(size / 2, size / 2)))

    # The launcher supplies the mask on a phone; standing alone in a README it needs its own.
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        [0, 0, size - 1, size - 1], radius=int(size * 0.22), fill=255
    )
    masked = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    masked.paste(image, (0, 0), mask)

    path.parent.mkdir(parents=True, exist_ok=True)
    masked.save(path)
    return True


def main() -> int:
    outside = [(offset, height) for offset, height in BARS if not fits(offset, height)]
    if outside:
        print("these bars would be clipped by a round launcher mask:")
        for offset, height in outside:
            print(f"  offset {offset:+.1f} height {height:.1f}")
        return 1

    (RES / "drawable" / "ic_launcher_foreground.xml").write_text(foreground(), encoding="utf-8")
    (RES / "drawable" / "ic_launcher_monochrome.xml").write_text(monochrome(), encoding="utf-8")
    (RES / "drawable" / "ic_launcher_background.xml").write_text(background(), encoding="utf-8")

    print(f"{len(BARS)} bars, all inside the {SAFE_RADIUS * 2:.0f}dp safe circle")
    png = DOCS / "icon.png"
    if write_png(png):
        print(f"preview: {png}")
    else:
        print("preview skipped: Pillow is not installed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
