"""Generates the map list the Meta screen filters by.

    python tools/make_maps.py

Blizzard's rates page can scope every hero's ban, pick and win rate to one map, which is the
only way to answer "who is actually played on King's Row". The page knows the maps but not
what mode each one is, and thirty maps in a flat list is a wall; OverFast knows the modes.
So the two are joined here and written out as Kotlin, rather than the app carrying a hand-
typed table that goes stale the next time a map ships.

Map names are left in English, like hero and ability names, because that is what the rates
page is keyed on.
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = (
    ROOT
    / "app"
    / "src"
    / "main"
    / "java"
    / "com"
    / "bellizia"
    / "owcompanion"
    / "ui"
    / "meta"
    / "MetaMaps.kt"
)

RATES = (
    "https://overwatch.blizzard.com/en-us/rates/"
    "?input=PC&map=all-maps&region=Europe&role=All&rq=1&tier=All"
)
OVERFAST = "https://overfast-api.tekrop.fr/maps"

USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"

# The order modes are shown in: the objective modes people queue for first, then the rest.
MODE_ORDER = ["control", "escort", "hybrid", "push", "flashpoint", "clash"]


def fetch(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8", "ignore")


def blizzard_maps() -> list[tuple[str, str]]:
    html = fetch(RATES)
    block = re.search(r'<select[^>]*data-label="map"[^>]*>(.*?)</select>', html, re.S)
    if not block:
        raise SystemExit("the rates page no longer has a map dropdown")
    pairs = re.findall(r'value="([^"]*)"[^>]*>([^<]*)<', block.group(1))
    return [(slug, label.strip()) for slug, label in pairs if slug != "all-maps"]


def main() -> int:
    maps = blizzard_maps()
    modes = {m["key"]: m.get("gamemodes", []) for m in json.loads(fetch(OVERFAST))}

    rows = []
    unknown = []
    for slug, label in maps:
        known = [g for g in modes.get(slug, []) if g in MODE_ORDER]
        if not known:
            unknown.append(label)
            continue
        rows.append((slug, label, known[0]))

    rows.sort(key=lambda r: (MODE_ORDER.index(r[2]), r[1]))

    entries = "\n".join(
        f'    MetaMap("{slug}", "{label}", "{mode}"),' for slug, label, mode in rows
    )
    OUT.write_text(
        f'''package com.bellizia.owcompanion.ui.meta

/**
 * A map the rates page can be scoped to, and the mode it is played in.
 *
 * Generated by tools/make_maps.py from Blizzard's own map dropdown joined with OverFast's
 * game modes - edit that, not this. Names stay in English because that is what the rates
 * page is keyed on.
 */
data class MetaMap(val slug: String, val label: String, val mode: String)

/** Every map the rates page will filter by, grouped by mode in the order shown. */
val MetaMaps: List<MetaMap> = listOf(
{entries}
)
''',
        encoding="utf-8",
    )

    print(f"wrote {len(rows)} maps to {OUT.relative_to(ROOT)}")
    for mode in MODE_ORDER:
        count = sum(1 for _, _, m in rows if m == mode)
        if count:
            print(f"  {mode:<12} {count}")
    if unknown:
        print(f"  no known mode, left out: {', '.join(unknown)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
